baseURL = 'https://example.org/'
title = 'Hugo GitHub Issue #10064'

defaultContentLanguageInSubdir = true

disableLanguages = ['de']

[languages.en]
contentDir = 'content/en'
languageCode = 'en-US'
languageName = 'English'
weight = 1

[languages.de]
contentDir = 'content/de'
languageCode = 'de-DE'
languageName = 'Deutsch'
weight = 2
