baseURL = 'https://example.org/foo/'
languageCode = 'en-us'
title = 'Hugo GitHub Issue #10585'

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false # default is true

[markup.goldmark.parser.attribute]
block = true # default is false
title = true # default is true

[params.render_hooks.link]
errorLevel = 'error' # ignore (default), warning, or error

[params.render_hooks.image]
errorLevel = 'error' # ignore (default), warning, or error

[permalinks]
books = '/publications/:slug/'
posts = '/:year/:month/:day/:slug/'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Books'
pageRef = '/books'
weight = 20

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 30

[[menu.main]]
name = 'Tests'
pageRef = '/tests'
weight = 40
